---
- name: Delete Directories Inside /app/ExecuteOracleScript
  hosts: your_target_hosts
  become: yes  # This will escalate privilege to root

  tasks:
    - name: Get list of directories to delete
      shell: find /app/ExecuteOracleScript -maxdepth 1 -type d ! -path /app/ExecuteOracleScript
      register: dirs_to_delete
      changed_when: false  # We don't want to treat directory listing as a change

    - name: Delete directories
      become: yes
      become_user: root
      file:
        path: "{{ item }}"
        state: absent
        recurse: yes
      loop: "{{ dirs_to_delete.stdout_lines }}"
      when: dirs_to_delete.stdout_lines | length > 0  # Only delete if there are directories to delete
