---
- hosts: all
  tasks:
    - name: Execute a command (replace with your desired task)
      command: echo "Sample output with ORA string"
      register: result
      ignore_errors: true

    - name: Check for specific strings in the output
      set_fact:
        found_strings: "{{ ['ORA', 'SP2', 'PLS'] | intersect(result.stdout.split()) }}"
      when: result.stdout is search('(ORA|SP2|PLS)')

    - name: Fail if specific strings are found
      fail:
        msg: "Found unwanted strings: {{ found_strings }}"
      when: found_strings | length > 0
