---
- name: Execute failDatabaseScript role and handle errors
  hosts: your_target_host_group_or_hostname
  tasks:
    - block:
        - name: Include failDatabaseScript role
          include_role:
            name: failDatabaseScript

      rescue:
        - name: Notify about the fatal error
          debug:
            msg: "A fatal error occurred while executing the failDatabaseScript role."

        - name: Fail the playbook with an explicit message
          fail:
            msg: "Stopping playbook execution due to fatal error in failDatabaseScript role."
