---
- name: Check for specific strings in db.txt log file
  hosts: your_target_host
  tasks:
    - name: Read the content of db.txt
      slurp:
        src: /path/to/db.txt
      register: file_content

    - name: Check for unwanted strings
      fail:
        msg: "Found an unwanted string in db.txt"
      when: >
        "'ORA' in file_content['content'] | b64decode or 
        'SP2' in file_content['content'] | b64decode or
        'PLS' in file_content['content'] | b64decode"
