- name: Configure Firewall
  hosts: all
  become: true
  tasks:
    - name: Add ports to public zone
      firewalld:
        zone: public
        port: "{{ item }}/tcp"
        permanent: yes
        state: enabled
      with_items:
        - 9090
        - 8080
        - 8843
        - 8943
        - 8443
        - 80
        - 443
        - 35957
    - name: Add services to public zone
      firewalld:
        zone: public
        service: "{{ item }}"
        permanent: yes
        state: enabled
      with_items:
        - http
        - https
    - name: Reload firewall
      firewalld:
        immediate: yes
        permanent: yes
        state: enabled

