---
- hosts: all
  become: true
  tasks:
    - name: List Linux users
      getent:
        database: passwd
      register: linux_users_output

    - name: Debug Linux users
      debug:
        var: linux_users_output.stdout_lines

    - name: Unlock all Linux users
      user:
        name: "{{ item }}"
        state: present
        password_lock: no
      with_items: "{{ linux_users_output.stdout_lines }}"

