---
- name: Create Tomcat user and add to sudoers
  hosts: all
  become: true

  vars:
    username: "tomcat"
    password: "Tomcat@2023"
    group_name: "tomcat"

  tasks:
    - name: Create user
      shell: |
        useradd "{{ username }}"
        echo "{{ password }}" | passwd --stdin "{{ username }}"
      register: user_created

    - name: Check if user exists
      command: id "{{ username }}"
      register: user_info

    - name: Fail if user does not exist
      fail:
        msg: "User {{ username }} was not created."
      when: user_created.rc != 0 or user_info.rc != 0

  tasks:
    - name: Create group
      group:
        name: "{{ group_name }}"
        state: present

    - name: Add user to group
      user:
        name: "{{ username }}"
        groups: "{{ group_name }}"
        append: yes

    - name: Check if user is in group
      shell: "id {{ username }} | grep '{{ group_name }}'"
      register: group_membership

    - name: Fail if user is not in group
      fail:
        msg: "User {{ username }} is not in group {{ group_name }}."
      when: group_membership.rc != 0

    - name: Add user to sudoers
      lineinfile:
        dest: "/etc/sudoers"
        state: present
        line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
      become: true
      become_method: sudo

    - name: Test sudo access
      shell: "sudo -u root whoami"
      become: true
      become_method: sudo
      register: sudo_output

    - name: Fail if sudo access fails
      fail:
        msg: "Sudo access test failed."
      when: sudo_output.rc != 0

