---
- name: Install Tomcat 9
  hosts: all
  become: true
  vars:
    tomcat_version: 9.0.55
  tasks:
    - name: Check if tomcat user exists
      getent:
        database: passwd
        key: tomcat
      register: tomcat_user_exists
      ignore_errors: true
    - name: Create Tomcat user if it does not exist
      user:
        name: tomcat
        comment: Tomcat User
        home: /opt/tomcat
        shell: /bin/nologin
        groups: tomcat
      when: tomcat_user_exists.rc != 0
    - name: Install Java
      package:
        name: java-1.8.0-openjdk
        state: present
    - name: Download Tomcat
      get_url:
        url: "https://downloads.apache.org/tomcat/tomcat-{{ tomcat_version.major }}/{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
        dest: /tmp
    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat-{{ tomcat_version }}.tar.gz
        dest: /opt
        remote_src: true
        creates: /opt/apache-tomcat-{{ tomcat_version }}
    - name: Set ownership and permissions
      file:
        path: /opt/apache-tomcat-{{ tomcat_version }}
        owner: tomcat
        group: tomcat
        mode: '0755'
        recurse: true
    - name: Create Tomcat service
      systemd:
        name: tomcat
        daemon_reload: yes
        enabled: yes
        state: started
        user: tomcat
        group: tomcat
        exec_start: /opt/apache-tomcat-{{ tomcat_version }}/bin/startup.sh
        exec_stop: /opt/apache-tomcat-{{ tomcat_version }}/bin/shutdown.sh

