---
- name: pull git repository
  hosts: all
  tasks:
    - name: Check if directory exists
      stat:
        path: /opt/prod
      register: dir_check

    - name: Pull git repository
      git:
        repo: master git@github.com:dougcardoso/douglab-repo1.git
        dest: /opt/prod
        update: yes
      when: dir_check.stat.exists == True
