---
- name: Pull from dev branch of Git repository via SSH
  hosts: ansible.douglab
  become: true
  vars:
    git_repo: git@github.com:dougcardoso/douglab-repo1.git
    git_branch: master
    target_dir: /opt/prod/
  tasks:
    - name: Fetch changes from Git repository
      git:
        repo: "{{ git_repo }}"
        dest: "{{ target_dir }}"
        accept_hostkey: yes
        key_file: /home/ansible/.ssh/id_rsa_git
        version: "{{ git_branch }}"
        update: yes

    - name: Set permissions on /opt/prod/
      become: true
      become_method: sudo
      command: sudo chmod -R 755 /opt/prod/

    - name: Set change owner on /opt/prod/
      become: true
      become_method: sudo
      command: sudo chown -R ansible:ansible /opt/prod/
